Created XBox Arm controller, Reformatted arm_node, launch files and config files, and improved documentation
HebiRobotics/hebi_ros2_examples pull request #2
Opened 2024-06-17 20:11 UTC by GogiPuttar

Functional X-box arm controller tested on A-2085-05 and A-2085-06 models

[HEBI_XBox.webm](https://github.com/HebiRobotics/hebi_ros2_examples/assets/59332714/cffcf79d-7ddb-4bc2-9b70-6dfb6cb5739b)
[HEBI_XBox.webm](https://github.com/HebiRobotics/hebi_ros2_examples/assets/59332714/cffcf79d-7ddb-4bc2-9b70-6dfb6cb5739b)

2024-06-17 20:21 UTC, hr1799 commented on CMakeLists.txt
> +if(moveit_ros_planning_interface_FOUND)
Does the xbox_arm node need moveit? If not, remove the if condition and the dependencies

2024-06-17 20:22 UTC, hr1799 commented on config/A-2084-01_params.yaml
>      families: [ "Arm" ]
Change families to "HEBIArm" in all config files for consistency.

2024-06-17 20:23 UTC, hr1799 requested changes
I have made two comments. Once updated, I can merge the branch.

2024-06-18 13:52 UTC, hr1799 commented on CMakeLists.txt
> +  moveit_msgs
Remove moveit dependencies -- line 72-74

2024-06-18 13:53 UTC, hr1799 commented on CMakeLists.txt
> +    xbox_arm
move to previous install (without moveit condition dependent)

2024-06-18 15:01 UTC, GogiPuttar commented
Made these changes and pushed to prototypes branch. Also included arm_node.launch in xbox_arm.launch

2024-06-18 15:04 UTC, hr1799 approved these changes
Looks good!

2024-06-18 15:05 UTC, merged